[versions]
sdk-compile = "36"
sdk-min = "24"
sdk-target = "36"

activity = "1.11.0"
androidGradlePlugin = "8.13.0"
androidMapsUtils = "3.19.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
fragment = "1.8.9"
glide = "5.0.5"
mapsSecretsGradlePlugin = "2.0.1"
material = "1.13.0"
multidex = "2.0.1"
navigationFragment = "2.9.5"
places = "5.0.0"
playServicesMaps = "19.2.0"
viewbinding = "8.13.0"
volley = "1.2.1"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
android-maps-utils = { module = "com.google.maps.android:android-maps-utils", version.ref = "androidMapsUtils" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
material = { module = "com.google.android.material:material", version.ref = "material" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
places = { module = "com.google.android.libraries.places:places", version.ref = "places" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
viewbinding = { module = "com.android.databinding:viewbinding", version.ref = "viewbinding" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "mapsSecretsGradlePlugin" }
